<?php

namespace ParkBundle\Entity;

/**
 * ComputerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Remove all computers
     */
    public function removeAll()
    {
        $computers = $this->findAll();
        if (!empty($computers) && is_array($computers)) {
            foreach ($computers as $computer) {
                if ($computer instanceof Computer) {
                    $this->_em->remove($computer);
                }
            }
            $this->_em->flush();
            return true;
        } else {
            return false;
        }
    }
}
