<?php

namespace ParkBundle\Entity;

/**
 * IpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnaffectedIps()
    {
        $qb = $this->createQueryBuilder("i");
        return $qb->addSelect("i")
            ->leftJoin("ParkBundle:Computer", "c", "WITH", "i.id = c.ip")
            ->andWhere($qb->expr()->isNull("c.ip"));
    }
}
